### PR TITLE
Compute R1 and PD without small flip angle approximation in mtsat

### LINKED ISSUE #40: Compute R1 and PD without small flip angle approximation in mtsat
In `mtsat`, compute R1 and PD (and incidentally, MTsat) without the small flip angle approximation. This follows from the suggestion in [Edwards et al., 2021](https://lup.lub.lu.se/search/publication/028387e6-909e-416a-97d4-85b95676e895). It is equivalent to setting `hmri_def.small_angle_approx = false` [in the hMRI-toolbox](https://github.com/hMRI-group/hMRI-toolbox/blob/035b484889e212e16afeac686998d55f91a43152/config/hmri_defaults.m#L162) (reflected in the [PD](https://github.com/hMRI-group/hMRI-toolbox/blob/035b484889e212e16afeac686998d55f91a43152/hmri_calc_A.m#L41) and [R1](https://github.com/hMRI-group/hMRI-toolbox/blob/035b484889e212e16afeac686998d55f91a43152/hmri_calc_R1.m#L41) computations).

### PR DESCRIPTION
**Pull request by jeremie-fouquet**
In mtsat, compute R1 and PD (and incidentally, MTsat) without the small flip angle approximation. This follows from the suggestion in [Edwards et al., 2021](https://lup.lub.lu.se/search/publication/028387e6-909e-416a-97d4-85b95676e895). It is equivalent to setting hmri_def.small_angle_approx = false [in the hMRI-toolbox](https://github.com/hMRI-group/hMRI-toolbox/blob/035b484889e212e16afeac686998d55f91a43152/config/hmri_defaults.m#L162) (reflected in the [PD](https://github.com/hMRI-group/hMRI-toolbox/blob/035b484889e212e16afeac686998d55f91a43152/hmri_calc_A.m#L41) and [R1](https://github.com/hMRI-group/hMRI-toolbox/blob/035b484889e212e16afeac686998d55f91a43152/hmri_calc_R1.m#L41) computations).

Fix #40.

### CODE REVIEW

**Comment by jeremie-fouquet** [comment]
I implemented this by entirely removing the small flip angle approximation. Let me know if you prefer to implement it as an option. I think it would mainly be for backward compatibility because I don't see other good reasons to still use the small flip angle approximation.

**Comment by spinicist** [comment]
>  I think it would mainly be for backward compatibility because I don't see other good reasons to still use the small flip angle approximation.

Exactly. I don't think I had seen this ESMRMB abstract before. If I read the figure correct, there is up to 5% difference in R1 in the center of the brain. That's big enough for people to notice, so big thanks for implementing this. But also big enough that giving people the choice of running the old approximation is a positive, so they can check it for themselves.

**Comment by jeremie-fouquet** [comment]
Great, ok, that makes sense. I'll try to implement this as an option and submit new commits for it soon.

**Comment by jeremie-fouquet** [comment]
The last commits implement the small flip angle approximation implemented as an option. Please do not hesitate to suggest changes; I still have much to learn about C++.

**Comment by spinicist** [comment]
This looks good, I have merged.

As a note on style I generally prefer something like:
`auto const x = which_one ? a + b : a - b;`
over
```auto x = a - b;
if (which_one) x = a + b;```
but this is a personal preference and the way you wrote it is fine.

**Pull request merged**
